### ISSUE TITLE
Limited Permissions - Failed to complete #create action: [You are not authorized to perform this operation.]

### ISSUE THREAD

**Issue by huntertj** [test-kitchen/kitchen-ec2#120]
In my environment we have limited access which is obtained through roles. I get the following when trying to converge. 
I am able to use the kitchen-ec2 0.8.0 version

```bash
09:45:28 {master} /c/dev/aw-p11tf12pm$ kitchen converge -l debug
-----> Starting Kitchen (v1.4.0)
D      Berksfile found at c:/dev/aw-p11tf12pm/Berksfile, loading Berkshelf
D      Berkshelf 3.2.4 library loaded
-----> Creating <default-centos-65>...
       Creating <>...
If you are not using an account that qualifies under the AWS
free-tier, you may be charged to run these suites. The charge
should be minimal, but neither Test Kitchen nor its maintainers
are responsible for your incurred costs.

D      Creating EC2 Instance..
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [You are not authorized to perform this operation.]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [You are not authorized to perform this operation.]
D      ---Nested Exception---
D      Class: Aws::EC2::Errors::UnauthorizedOperation
D      Message: You are not authorized to perform this operation.
D      ------Backtrace-------
D      c:/Users/tim/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.0.42/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
D      c:/Users/tim/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.0.42/lib/seahorse/client/plugins/param_conversion.rb:22:in `call'

D      c:/Users/tim/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.0.42/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
D      c:/Users/tim/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.0.42/lib/seahorse/client/plugins/response_target.rb:18:in `call' D      c:/Users/tim/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.0.42/lib/seahorse/client/request.rb:70:in `send_request'
D      c:/Users/tim/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-core-2.0.42/lib/seahorse/client/base.rb:216:in `block (2 levels) in define_operation_methods'
D      c:/Users/tim/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-resources-2.0.42/lib/aws-sdk-resources/request.rb:24:in `call'
D      c:/Users/tim/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-resources-2.0.42/lib/aws-sdk-resources/operations.rb:41:in `call'
D      c:/Users/tim/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-resources-2.0.42/lib/aws-sdk-resources/operations.rb:61:in `call'
D      c:/Users/tim/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-resources-2.0.42/lib/aws-sdk-resources/resource.rb:147:in `load'
D      c:/Users/tim/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-resources-2.0.42/lib/aws-sdk-resources/resource.rb:120:in `data'
D      c:/Users/tim/.chefdk/gem/ruby/2.1.0/gems/aws-sdk-resources-2.0.42/lib/aws-sdk-resources/resource.rb:223:in `block in add_data_attribute'
D      c:/Users/tim/.chefdk/gem/ruby/2.1.0/gems/kitchen-ec2-0.9.0/lib/kitchen/driver/aws/instance_generator.rb:117:in `debug_if_root_device'
D      c:/Users/tim/.chefdk/gem/ruby/2.1.0/gems/kitchen-ec2-0.9.0/lib/kitchen/driver/aws/instance_generator.rb:106:in `block_device_mappings'
D      c:/Users/tim/.chefdk/gem/ruby/2.1.0/gems/kitchen-ec2-0.9.0/lib/kitchen/driver/aws/instance_generator.rb:55:in `ec2_instance_data'
D      c:/Users/tim/.chefdk/gem/ruby/2.1.0/gems/kitchen-ec2-0.9.0/lib/kitchen/driver/ec2.rb:283:in `submit_server'
D      c:/Users/tim/.chefdk/gem/ruby/2.1.0/gems/kitchen-ec2-0.9.0/lib/kitchen/driver/ec2.rb:185:in `create'
D      c:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:424:in `public_send'
D      c:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:424:in `block in perform_action'

D      c:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:488:in `call'
D      c:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:488:in `synchronize_or_call'
D      c:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:453:in `block in action'
D      c:/opscode/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D      c:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:452:in `action'
D      c:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:424:in `perform_action'
D      c:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:352:in `create_action'
D      c:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:341:in `block in transition_to' D      c:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:340:in `each'
D      c:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:340:in `transition_to'
D      c:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:138:in `converge'
D      c:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/command.rb:176:in `public_send'
D      c:/opscode/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
D      ----------------------
```

**Comment by huntertj** [comment]
please close, this was my own mistake, mismatch of keys
