### ISSUE TITLE
[Network interfaces and an instance-level security groups may not be specified on the same request]

### ISSUE THREAD

**Issue by kplimack** [test-kitchen/kitchen-ec2#127]
I get the warnings, they have meaning, but this error thats killing me does not.  theres nothing in the changelogs or readme as far as I can tell.
```
+ kitchen test
-----> Starting Kitchen (v1.4.0)
$$$$$$ WARN: The driver[Kitchen::Driver::Ec2] config key `ebs_delete_on_termination` is deprecated, please use `block_device_mappings`
$$$$$$ WARN: The driver[Kitchen::Driver::Ec2] config key `ssh_key` is deprecated, please use `transport.ssh_key`
$$$$$$ WARN: The driver[Kitchen::Driver::Ec2] config key `username` is deprecated, please use `transport.username`
$$$$$$ WARN: The driver[Kitchen::Driver::Ec2] config key `flavor_id` is deprecated, please use `instance_type`
$$$$$$ WARN: aws_access_key_id has been deprecated, please use ENV['AWS_ACCESS_KEY_ID'] or ~/.aws/credentials.  See the README for more details
$$$$$$ WARN: aws_secret_access_key has been deprecated, please use ENV['AWS_SECRET_ACCESS_KEY'] or ~/.aws/credentials.  See the README for more details
-----> Cleaning up any prior instances of <default-debian-ec2>
-----> Destroying <default-debian-ec2>...
       Finished destroying <default-debian-ec2> (0m0.00s).
-----> Testing <default-debian-ec2>
-----> Creating <default-debian-ec2>...
       Creating <>...
If you are not using an account that qualifies under the AWS
free-tier, you may be charged to run these suites. The charge
should be minimal, but neither Test Kitchen nor its maintainers
are responsible for your incurred costs.
 
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [Network interfaces and an instance-level security groups may not be specified on the same request]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
Build step 'Execute shell' marked build as failure
ERROR: Publisher jp.skypencil.jenkins.regression.RegressionReportNotifier aborted due to exception
java.lang.NoSuchMethodError: hudson.model.AbstractBuild.getTestResultAction()Lhudson/tasks/test/AbstractTestResultAction;
	at jp.skypencil.jenkins.regression.RegressionReportNotifier.perform(RegressionReportNotifier.java:97)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
	at hudson.model.Run.execute(Run.java:1775)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:89)
	at hudson.model.Executor.run(Executor.java:240)
[ci-game] evaluating rule: Build result
[ci-game] evaluating rule: Increased number of passed tests
[ci-game] evaluating rule: Decreased number of passed tests
[ci-game] evaluating rule: Increased number of failed tests
[ci-game] evaluating rule: Decreased number of failed tests
[ci-game] evaluating rule: Increased number of skipped tests
[ci-game] evaluating rule: Decreased number of skipped tests
[ci-game] evaluating rule: Changed number of compiler warnings
Warning: you have no plugins providing access control for builds, so falling back to legacy behavior of permitting any downstream builds to be triggered
Notifying upstream projects of job completion
Finished: FAILURE
```

**Comment by tyler-ball** [comment]
Right you are!  I fixed subnets so they are reported on the network_interface, but I need to also report security_groups on the network interface as well.  The fix for this will go out in a patch release.

**Comment by kplimack** [comment]
@tyler-ball i build and installed the kitchen-ec2 gem from master, but now I'm running into https://github.com/chef/chef-dk/issues/309
```
╰─➤  kitchen create -l debug                                                                                                                                                    1 ↵
-----> Starting Kitchen (v1.4.0)
D      Berksfile found at /Users/eulipion/repos/chef/cookbooks/derp-base/Berksfile, loading Berkshelf
D      Berkshelf 3.2.4 library loaded
-----> Creating <default-debian-ec2>...
       Creating <>...
If you are not using an account that qualifies under the AWS
free-tier, you may be charged to run these suites. The charge
should be minimal, but neither Test Kitchen nor its maintainers
are responsible for your incurred costs.

D      Creating EC2 Instance..
/opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:180:in `join': No live threads left. Deadlock? (fatal)
	from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:180:in `map'
	from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:180:in `run_action'
	from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command/action.rb:39:in `block in call'
	from /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
	from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command/action.rb:37:in `call'
	from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/cli.rb:56:in `perform'
	from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/cli.rb:171:in `block (2 levels) in <class:CLI>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/cli.rb:308:in `invoke_task'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /opt/chefdk/embedded/apps/test-kitchen/bin/kitchen:13:in `block in <top (required)>'
	from /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/errors.rb:154:in `with_friendly_errors'
	from /opt/chefdk/embedded/apps/test-kitchen/bin/kitchen:13:in `<top (required)>'
	from /opt/chefdk/bin/kitchen:15:in `load'
	from /opt/chefdk/bin/kitchen:15:in `<main>'
```

```
╰─➤  chef gem list                                                                                                                                                              1 ↵

*** LOCAL GEMS ***

activesupport (4.2.1, 4.1.8, 4.1.7, 3.2.21)
addressable (2.3.8)
akami (1.3.0, 1.2.2)
app_conf (0.4.2)
appbundler (0.4.0)
archive (0.0.6)
archive-tar-minitar (0.5.2)
aruba (0.6.2)
ast (2.0.0)
astrolabe (1.3.0)
aws-sdk (2.0.45)
aws-sdk-core (2.0.45)
aws-sdk-resources (2.0.45)
aws-sdk-v1 (1.64.0, 1.59.1)
axiom-types (0.1.1)
berkshelf (3.2.4, 3.2.3, 3.2.1, 3.2.0, 3.1.4)
berkshelf-api-client (1.2.1)
bigdecimal (1.2.4)
buff-config (1.0.1, 0.4.0)
buff-extensions (1.0.0, 0.5.0)
buff-ignore (1.1.1)
buff-ruby_engine (0.1.0)
buff-shell_out (0.2.0)
builder (3.2.2)
bundler (1.7.12)
cane (2.6.2)
celluloid (0.16.0, 0.16.0.pre3)
celluloid-io (0.16.2, 0.16.1)
CFPropertyList (2.3.1, 2.2.8)
chef (12.3.0, 12.0.3)
chef-dk (0.5.1)
chef-metal (0.12.1)
chef-metal-fog (0.9)
chef-metal-vagrant (0.6)
chef-provisioning (1.1.1, 0.20.1)
chef-provisioning-aws (1.1.1)
chef-provisioning-azure (0.3.2)
chef-provisioning-docker (0.6)
chef-provisioning-fog (0.13.2)
chef-provisioning-vagrant (0.8.3)
chef-vault (2.4.0)
chef-zero (4.2.1, 3.2.1, 1.5.6)
cheffish (1.1.2, 0.10, 0.8.3)
chefspec (4.2.0, 4.1.1)
childprocess (0.5.6)
chunky_png (1.3.3)
cleanroom (1.0.0)
codeclimate-test-reporter (0.4.7)
coderay (1.1.0)
coercible (1.0.0)
coffee-script (2.3.0)
coffee-script-source (1.8.0)
colorize (0.7.3)
compass (1.0.1)
compass-core (1.0.1)
compass-import-once (1.0.5)
configuration (1.3.4)
cookbook-omnifetch (0.2.1)
countloc (0.4.0)
coveralls (0.7.1)
crack (0.4.2)
cucumber (2.0.0, 1.3.19)
cucumber-core (1.1.3)
dep-selector-libgecode (1.0.2)
dep_selector (1.0.3)
descendants_tracker (0.0.4)
diff-lcs (1.2.5)
diffy (3.0.7)
docile (1.1.5)
docker-api (1.21.4, 1.11.2)
domain_name (0.5.24)
droplet_kit (1.1.2)
em-websocket (0.5.1)
em-winrm (0.6.0)
equalizer (0.0.11)
erubis (2.7.0)
eventmachine (1.0.7, 1.0.3)
excon (0.45.3, 0.42.0, 0.31.0)
execjs (2.2.2)
fakefs (0.6.7)
faraday (0.9.1, 0.8.9)
fauxhai (2.3.0, 2.2.0)
ffi (1.9.8, 1.9.6, 1.9.4)
ffi-yajl (2.2.0, 1.4.0, 1.3.1, 1.2.0)
finstyle (1.4.0, 1.3.0, 1.0.0)
fission (0.5.0)
fog (1.29.0, 1.25.0, 1.20.0)
fog-atmos (0.1.0)
fog-aws (0.1.2)
fog-brightbox (0.7.1, 0.7.0)
fog-core (1.30.0, 1.25.0)
fog-ecloud (0.1.1)
fog-json (1.0.1, 1.0.0)
fog-local (0.2.1)
fog-powerdns (0.1.1)
fog-profitbricks (0.0.2, 0.0.1)
fog-radosgw (0.0.4, 0.0.3)
fog-riakcs (0.1.0)
fog-sakuracloud (1.0.1, 0.1.1)
fog-serverlove (0.1.2)
fog-softlayer (0.4.5, 0.3.25)
fog-storm_on_demand (0.1.1)
fog-terremark (0.1.0, 0.0.3)
fog-vmfusion (0.1.0, 0.0.1)
fog-voxel (0.1.0, 0.0.2)
fog-xml (0.1.2, 0.1.1)
foodcritic (4.0.0)
formatador (0.2.5)
fuubar (1.3.3)
gherkin (2.12.2)
gist (4.3.0)
git (1.2.9.1)
grape (0.11.0)
grape-msgpack (0.1.2)
gssapi (1.2.0, 1.0.3)
guard (2.12.5)
guard-compat (1.2.1)
guard-rspec (4.5.0)
gyoku (1.3.1, 1.2.2)
haml (4.0.5)
happymapper (0.4.1)
hashie (2.1.2)
highline (1.7.2)
hike (1.2.3)
hitimes (1.2.2)
hooks (0.4.0)
http (0.8.4)
http-cookie (1.0.2)
http-form_data (1.0.1)
http_parser.rb (0.6.0)
httpclient (2.6.0.1, 2.5.1)
httpi (0.9.7)
i18n (0.7.0)
ice_nine (0.11.1)
inflecto (0.0.2)
inifile (2.0.2)
io-console (0.4.2)
ipaddress (0.8.0)
jmespath (1.0.2)
json (1.8.2, 1.8.1)
kartograph (0.2.0)
kitchen-digitalocean (0.8.2)
kitchen-docker (2.1.0)
kitchen-ec2 (0.10.0.dev.1, 0.8.0)
kitchen-vagrant (0.18.0, 0.17.0)
knife-block (0.1.1)
knife-bulkchangeenvironment (0.1.1)
knife-cleanup (0.0.5)
knife-config (1.1.0)
knife-container (0.2.4)
knife-docker (0.0.2)
knife-ec2 (0.8.0)
knife-essentials (1.5.6)
knife-flip (0.1.9)
knife-github-cookbooks (0.1.8)
knife-ohno (0.1.0)
knife-preflight (0.1.7)
knife-solo (0.4.2)
knife-solo_data_bag (1.1.0)
knife-solve (1.0.1)
knife-spork (1.5.0)
knife-windows (0.8.4, 0.8.2, 0.8.0)
kramdown (1.5.0)
launchy (0.4.0)
libv8 (3.16.14.7, 3.11.8.17 x86_64-darwin-12)
libxml-ruby (2.7.0)
libyajl2 (1.2.0, 1.1.0)
listen (2.10.0)
little-plugger (1.1.3)
logging (1.8.2)
lumberjack (1.0.9)
macaddr (1.7.1)
maruku (0.7.2)
metaclass (0.0.4)
method_source (0.8.2)
middleman (3.3.6)
middleman-core (3.3.6)
middleman-gh-pages (0.0.3)
middleman-livereload (3.3.4)
middleman-sprockets (3.3.10)
middleman-syntax (2.0.0)
mime-types (2.5)
mini_portile (0.6.2, 0.6.1, 0.6.0)
minitar (0.5.4)
minitest (5.6.1, 5.4.3, 4.7.5)
mixlib-authentication (1.3.0)
mixlib-cli (1.5.0)
mixlib-config (2.2.1, 2.1.0)
mixlib-log (1.6.0)
mixlib-shellout (2.0.1, 1.6.1, 1.6.0)
mocha (1.1.0)
moneta (0.6.0)
msgpack (0.5.11)
multi_json (1.11.0)
multi_test (0.1.2)
multi_xml (0.5.5)
multipart-post (2.0.0, 1.2.0)
nenv (0.2.0)
net-http-persistent (2.9.4)
net-scp (1.2.1)
net-ssh (2.9.2)
net-ssh-gateway (1.2.0)
net-ssh-multi (1.2.1)
netrc (0.10.3)
nio4r (1.1.0)
nokogiri (1.6.6.2, 1.6.5, 1.6.3.1)
nori (2.5.0, 1.1.5)
notiffany (0.0.6)
octokit (3.8.0, 3.7.0, 3.5.2, 3.4.2, 3.3.1)
ohai (8.3.0, 8.2.0)
opennebula (4.10.1)
padrino-helpers (0.12.4)
padrino-support (0.12.4)
paint (1.0.0)
parallel (1.4.1, 1.3.3)
parser (2.2.2.2, 2.2.0.pre.8)
plist (3.1.0)
polyglot (0.3.5)
powerpack (0.0.9)
pry (0.10.1)
psych (2.0.5)
puma (1.6.3)
rack (1.6.1, 1.6.0, 1.5.2)
rack-accept (0.4.5)
rack-livereload (0.3.15)
rack-mount (0.8.3)
rack-test (0.6.2)
rainbow (2.0.0)
rake (10.4.2, 10.4.1, 10.1.1, 10.1.0, 0.9.6)
rb-fsevent (0.9.4)
rb-inotify (0.9.5)
rbtrace (0.4.7)
rbvmomi (1.8.2)
rdoc (4.1.0)
redcarpet (3.1.2)
reel (0.5.0)
ref (1.0.5)
resource_kit (0.1.1)
rest-client (1.8.0)
retryable (2.0.1, 1.3.6)
ridley (4.1.2, 4.1.1, 4.1.0, 2.5.1)
rouge (1.7.2)
rspec (3.2.0, 3.0.0, 2.99.0)
rspec-core (3.2.3, 3.1.7, 3.0.4, 2.99.2)
rspec-expectations (3.2.1, 3.0.4, 2.99.2)
rspec-its (1.2.0, 1.1.0)
rspec-mocks (3.2.1, 3.1.3, 3.0.4, 2.99.3)
rspec-support (3.2.2, 3.1.2, 3.0.4)
rspec_junit_formatter (0.2.2, 0.2.1)
rubocop (0.28.0, 0.27.1, 0.27.0, 0.24.1)
ruby-progressbar (1.7.5, 1.7.0)
ruby-shadow (2.4.1)
ruby_gntp (0.3.4)
rubyntlm (0.4.0, 0.1.1)
rubyzip (1.1.7)
rufus-lru (1.0.5)
safe_yaml (1.0.4)
sass (3.4.7)
savon (0.9.5)
sawyer (0.6.0)
semverse (1.2.1)
serverspec (2.17.0, 2.14.1, 2.7.0)
shellany (0.0.1)
simplecov (0.10.0, 0.7.1)
simplecov-html (0.10.0, 0.7.1)
slop (3.6.0)
solve (1.2.1)
specinfra (2.32.0, 2.30.2, 2.10.1)
spork (0.9.2)
sprockets (2.12.3)
sprockets-helpers (1.1.0)
sprockets-sass (1.2.0)
stuartpreston-azure-sdk-for-ruby (0.7.1)
sys-proctable (0.9.8 universal-darwin)
systemu (2.6.5)
term-ansicolor (1.3.0)
test-kitchen (1.4.0)
test-unit (2.1.5.0)
therubyracer (0.11.3)
thor (0.19.1)
thread_safe (0.3.5)
tilt (1.4.1)
timers (4.0.1, 4.0.0)
tins (1.5.1)
treetop (1.5.3, 1.4.15)
trollop (2.0)
tzinfo (1.2.2)
uber (0.0.10)
uglifier (2.5.3)
unf (0.1.4)
unf_ext (0.0.7.1)
uuid (2.3.7)
uuidtools (2.1.5)
varia_model (0.4.0, 0.3.2)
virtus (1.0.5)
wasabi (1.0.0)
webmock (1.21.0)
websocket_parser (1.0.0)
winrm (1.3.2, 1.2.0)
winrm-s (0.2.4, 0.2.0)
winrm-transport (1.0.0)
wmi-lite (1.0.0)
yajl-ruby (1.2.1)
yard (0.8.7.6)
```

**Comment by tyler-ball** [comment]
@kplimack Did you try moving `~/.chefdk` to `~/.chefdk_old`?

**Comment by kplimack** [comment]
i tried blowing away the old installation and installing fresh chefdk.
If I move the ~/.chefdk dir out of the way, I get
```
D      ------Exception-------
D      Class: Kitchen::ClientError
D      Message: Could not load the 'ec2' driver from the load path. Please
ensure that your driver is installed as a gem or included in your Gemfile
if using Bundler.
D      ---Nested Exception---
D      Class: LoadError
D      Message: cannot load such file -- kitchen/driver/ec2
```

**Comment by kplimack** [comment]
ok, blew away the old chefdk, moved ~/.chefdk out of the way, installed chefdk clean, installed kitchen-ec2 gem from local build, working again!

**Comment by kplimack** [comment]
well, now TK is actually waiting on the node to become ready, but it's getting terminated and TK is waiting forever for a dead node.  uh oh

**Comment by jcderose** [comment]
Hi @tyler-ball, I'm still experiencing the original error in v0.9.1 of the code (see snippets below). Is there a different way I should declare my subnet, security group, and "associate_public_IP" attributes? 

```
➜  chef gem list | grep kitchen
kitchen-ec2 (0.9.1)
test-kitchen (1.4.0)
```
```
➜  kitchen create default-amazon
-----> Starting Kitchen (v1.4.0)
-----> Creating <default-amazon>...
       Creating <>...

>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [Network interfaces and an instance-level security groups may not be specified on the same request]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

```
---
driver:
  name: ec2
  security_group_ids: ["sg-1234"]
  region: us-west-2
  availability_zone: us-west-2a
  require_chef_omnibus: true
  subnet_id: subnet-5678
  image_id: "ami-ff527ecf"
  associate_public_ip: true

provisioner:
  name: chef_solo

platforms:
  - name: amazon

suites:
  - name: default
    run_list:
    attributes:
```

**Comment by antonosmond** [comment]
I'm having the exact same problem:
```
---
driver:
  name: ec2
  region: eu-west-1
  availability_zone: eu-west-1a
  network-attachment: subnet_id: subnet-2a610e4f
  instance_type: t2.micro
  require_chef_omnibus: true
  aws_ssh_key_id: ninja-test
  security_group_ids: ["sg-3fa6a148"]
  associate_public_ip: true
```
Results in following error:
```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [Network interfaces and an instance-level security groups may not be specified on the same request]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

**Comment by tyler-ball** [comment]
@antonosmond and @jcderose - the fix is currently sitting in master but it hasn't been released yet.  If you could test the fix locally, I would appreciate it!  Add a Gemfile to your cookbook with the following contents:

```ruby
source 'https://rubygems.org'

gem "test-kitchen"
gem "kitchen-ec2", git: "https://github.com/test-kitchen/kitchen-ec2"
gem "berkshelf"
```

Run a `bundle install` and then prepend your kitchen commands with `bundle exec`.

**Comment by tyler-ball** [comment]
Actually, scratch all that - I just released kitchen-ec2 0.9.2 (hopefully) with the fix.  Can you try the latest version and see if it works for you?

**Comment by jcderose** [comment]
@tyler-ball, I just updated to kitchen-ec2 0.9.2 and ran kitchen create again - same error message.

**Comment by tyler-ball** [comment]
Super weird - @jcderose can you gist the full output of `kitchen diagnose --all`?  And then open up https://github.com/test-kitchen/kitchen-ec2/blob/v0.9.2/lib/kitchen/driver/aws/instance_generator.rb#L82 locally and put a `require 'pry'; binding.pry` statement right above line 82, type `i` when it hits the breakpoint and put the contents of that object into the same gist?

We'll get to the bottom of this!

**Comment by jcderose** [comment]
Here's the gist for my `kitchen diagnose --all` output: https://gist.github.com/jcderose/0b1c8e27f6a2d2a49fb5

I edited my local copy of the instance_generator.rb file you referenced and added the `require 'pry'; binding.pry` and re-ran my `kitchen create` command but it did not give me any breakpoint. Let me know if I need to run a different command to test this.

**Comment by tyler-ball** [comment]
@jcderose because it did not hit the breakpoint, it makes me think we're running into an issue where an old version of kitchen-ec2 is getting loaded.  Are you using the ChefDK?  How are you managing and installing gems?

**Comment by jcderose** [comment]
Yes, I'm using the most recent versions of ChefDK and the kitchen-ec2 driver.

```
➜  ~  chef-client --version
Chef: 12.3.0
```

```
➜  ~  chef gem list | grep kitchen
kitchen-ec2 (0.9.2)
test-kitchen (1.4.0)
```

I'm managing and installing gems via `chef gem install` and `chef gem update`.

**Comment by jcderose** [comment]
@tyler-ball, you were right: my shell wasn't using the embedded ruby/gems in the ChefDK directory. I fixed my path and was able to run `kitchen create

**Comment by tyler-ball** [comment]
@jcderose woohoo!  I'm going to close this then
