### ISSUE TITLE
kitchen destroy bombs trying to destroy non-existent instances

### ISSUE THREAD

**Issue by kplimack** [test-kitchen/kitchen-ec2#143]
````
jenkins@use1d-build101:~/jenkins-data/jobs/chef-base - Integration Testing/workspace/cookbooks/derp-base$ kitchen destroy -l debug
-----> Starting Kitchen (v1.4.0)
D      Berksfile found at /data/jenkins-data/jobs/chef-base - Integration Testing/workspace/cookbooks/showmobile-base/Berksfile, loading Berkshelf
D      Berkshelf 3.2.3 library loaded
-----> Destroying <default-debian-ec2>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #destroy action: [The instance ID 'i-37e87ac8' does not exist]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #destroy action: [The instance ID 'i-37e87ac8' does not exist]
D      ---Nested Exception---
D      Class: Aws::EC2::Errors::InvalidInstanceIDNotFound
D      Message: The instance ID 'i-37e87ac8' does not exist
D      ------Backtrace-------
D      /usr/local/rvm/gems/ruby-1.9.3-p547/gems/aws-sdk-core-2.0.47/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
D      /usr/local/rvm/gems/ruby-1.9.3-p547/gems/aws-sdk-core-2.0.47/lib/seahorse/client/plugins/param_conversion.rb:22:in `call'
D      /usr/local/rvm/gems/ruby-1.9.3-p547/gems/aws-sdk-core-2.0.47/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
D      /usr/local/rvm/gems/ruby-1.9.3-p547/gems/aws-sdk-core-2.0.47/lib/seahorse/client/plugins/response_target.rb:18:in `call'
D      /usr/local/rvm/gems/ruby-1.9.3-p547/gems/aws-sdk-core-2.0.47/lib/seahorse/client/request.rb:70:in `send_request'
D      /usr/local/rvm/gems/ruby-1.9.3-p547/gems/aws-sdk-core-2.0.47/lib/seahorse/client/base.rb:216:in `block (2 levels) in define_operation_methods'
D      /usr/local/rvm/gems/ruby-1.9.3-p547/gems/aws-sdk-resources-2.0.47/lib/aws-sdk-resources/request.rb:24:in `call'
D      /usr/local/rvm/gems/ruby-1.9.3-p547/gems/aws-sdk-resources-2.0.47/lib/aws-sdk-resources/operations.rb:41:in `call'
D      /usr/local/rvm/gems/ruby-1.9.3-p547/gems/aws-sdk-resources-2.0.47/lib/aws-sdk-resources/operation_methods.rb:19:in `block in add_operation'
D      /usr/local/rvm/gems/ruby-1.9.3-p547/gems/kitchen-ec2-0.10.0.dev.3/lib/kitchen/driver/ec2.rb:234:in `destroy'
D      /usr/local/rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:424:in `public_send'
D      /usr/local/rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:424:in `block in perform_action'
D      /usr/local/rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:488:in `call'
D      /usr/local/rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:488:in `synchronize_or_call'
D      /usr/local/rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:453:in `block in action'
D      /usr/local/rvm/rubies/ruby-1.9.3-p547/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
D      /usr/local/rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:452:in `action'
D      /usr/local/rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:424:in `perform_action'
D      /usr/local/rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:411:in `destroy_action'
D      /usr/local/rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:341:in `block in transition_to'
D      /usr/local/rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:340:in `each'
D      /usr/local/rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:340:in `transition_to'
D      /usr/local/rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:171:in `destroy'
D      /usr/local/rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.4.0/lib/kitchen/command.rb:176:in `public_send'
D      /usr/local/rvm/gems/ruby-1.9.3-p547/gems/test-kitchen-1.4.0/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
D      ----------------------
````
````
gem list | egrep '(kitchen|ec2|chef|aws)'
aws (2.10.2)
aws-sdk (2.0.47)
aws-sdk-core (2.0.47)
aws-sdk-resources (2.0.47)
aws-sdk-v1 (1.59.1)
chef (11.12.8)
chef-zero (2.0.2)
fog-aws (0.1.1, 0.1.0)
kitchen-ec2 (0.10.0.dev.3, 0.8.0)
test-kitchen (1.4.0)
````

**Comment by kplimack** [comment]
purged .kitchen directory, fixed
