### ISSUE TITLE
expected params[:network_interfaces][0][:groups] to be an array

### ISSUE THREAD

**Issue by opsline-radek** [test-kitchen/kitchen-ec2#144]
I'm getting the following exception on 0.9.3

```
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [expected params[:network_interfaces][0][:groups] to be an array]
D      ---Nested Exception---
D      Class: ArgumentError
D      Message: expected params[:network_interfaces][0][:groups] to be an array
D      ------Backtrace-------
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.47/lib/seahorse/client/param_validator.rb:24:in `validate!'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.47/lib/seahorse/client/param_validator.rb:9:in `validate!'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.47/lib/seahorse/client/plugins/param_validation.rb:21:in `call'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.47/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.47/lib/seahorse/client/plugins/param_conversion.rb:22:in `call'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.47/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.47/lib/seahorse/client/plugins/response_target.rb:18:in `call'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.47/lib/seahorse/client/request.rb:70:in `send_request'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.0.47/lib/seahorse/client/base.rb:216:in `block (2 levels) in define_operation_methods'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.0.47/lib/aws-sdk-resources/request.rb:24:in `call'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.0.47/lib/aws-sdk-resources/operations.rb:41:in `call'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.0.47/lib/aws-sdk-resources/operations.rb:87:in `call'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.0.47/lib/aws-sdk-resources/operation_methods.rb:19:in `block in add_operation'
D      /opt/chef.12.2.1/embedded/lib/ruby/gems/2.1.0/gems/kitchen-ec2-0.9.3/lib/kitchen/driver/aws/client.rb:82:in `create_instance'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/kitchen-ec2-0.9.3/lib/kitchen/driver/ec2.rb:300:in `submit_server'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/kitchen-ec2-0.9.3/lib/kitchen/driver/ec2.rb:188:in `create'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:424:in `public_send'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:424:in `block in perform_action'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:488:in `call'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:488:in `synchronize_or_call'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:453:in `block in action'
D      /opt/chef/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:452:in `action'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:424:in `perform_action'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:352:in `create_action'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:341:in `block in transition_to'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:340:in `each'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:340:in `transition_to'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/instance.rb:138:in `converge'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/command.rb:176:in `public_send'
D      /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.4.0/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
D      ----------------------
```

**Comment by tyler-ball** [comment]
Hey @opsline-radek - what does the output of your `kitchen diagnose` look like?

**Comment by apulido-carecloud** [comment]
Had the same problem. Make sure security_group_ids is an array,  security_group_ids: [ sg-xxxxxx ]
That fixed it for me.

**Comment by tyler-ball** [comment]
I'm going to close this since there hasn't been any movement in 3 weeks.  I think its a valid error coming back from AWS because (as @apulido-carecloud said) they want security_group_ids to be an array.

Something we can do is make sure we automatically make `security_group_ids` an array if users only pass us 1 value.

**Comment by opsline-radek** [comment]
Making the security_group_ids an array does the trick. Thank you.

**Comment by fnichol** [comment]
@opsline-radek I've pushed #166 which should accommodate a string value--less to think about in the future!
