### ISSUE TITLE
Issues under high concurrency 

### ISSUE THREAD

**Issue by i11** [test-kitchen/kitchen-ec2#176]
Running test action over 20 instances and for one of them getting this:
```
I, [2015-07-15T13:15:46.556544 #10402]  INFO -- Kitchen: -----> Verifying <vm>...
E, [2015-07-15T13:17:19.993207 #10402] ERROR -- Kitchen: ------Exception-------
E, [2015-07-15T13:17:19.993247 #10402] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2015-07-15T13:17:19.993273 #10402] ERROR -- Kitchen: Message: Failed to complete #create action: [undefined method `image' for #<Aws::EC2::Resource>]
E, [2015-07-15T13:17:19.993327 #10402] ERROR -- Kitchen: ---Nested Exception---
E, [2015-07-15T13:17:19.993373 #10402] ERROR -- Kitchen: Class: NoMethodError
E, [2015-07-15T13:17:19.993397 #10402] ERROR -- Kitchen: Message: undefined method `image' for #<Aws::EC2::Resource>
E, [2015-07-15T13:17:19.993420 #10402] ERROR -- Kitchen: ------Backtrace-------
E, [2015-07-15T13:17:19.993449 #10402] ERROR -- Kitchen: /my/user/home/.bundle/gems/kitchen-ec2-0.10.0/lib/kitchen/driver/aws/instance_generator.rb:129:in `debug_if_root_device'
E, [2015-07-15T13:17:19.993490 #10402] ERROR -- Kitchen: /my/user/home/.bundle/gems/kitchen-ec2-0.10.0/lib/kitchen/driver/aws/instance_generator.rb:119:in `block_device_mappings'
E, [2015-07-15T13:17:19.993513 #10402] ERROR -- Kitchen: /my/user/home/.bundle/gems/kitchen-ec2-0.10.0/lib/kitchen/driver/aws/instance_generator.rb:54:in `ec2_instance_data'
E, [2015-07-15T13:17:19.993536 #10402] ERROR -- Kitchen: /my/user/home/.bundle/gems/kitchen-ec2-0.10.0/lib/kitchen/driver/ec2.rb:288:in `submit_server'
E, [2015-07-15T13:17:19.993558 #10402] ERROR -- Kitchen: /my/user/home/.bundle/gems/kitchen-ec2-0.10.0/lib/kitchen/driver/ec2.rb:192:in `create'
E, [2015-07-15T13:17:19.993580 #10402] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:424:in `public_send'
E, [2015-07-15T13:17:19.993602 #10402] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:424:in `block in perform_action'
E, [2015-07-15T13:17:19.993630 #10402] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:488:in `call'
E, [2015-07-15T13:17:19.993673 #10402] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:488:in `synchronize_or_call'
E, [2015-07-15T13:17:19.993697 #10402] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:453:in `block in action'
E, [2015-07-15T13:17:19.993723 #10402] ERROR -- Kitchen: /opt/rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
E, [2015-07-15T13:17:19.993745 #10402] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:452:in `action'
E, [2015-07-15T13:17:19.993782 #10402] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:424:in `perform_action'
E, [2015-07-15T13:17:19.993805 #10402] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:352:in `create_action'
E, [2015-07-15T13:17:19.993828 #10402] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:341:in `block in transition_to'
E, [2015-07-15T13:17:19.993850 #10402] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:340:in `each'
E, [2015-07-15T13:17:19.993873 #10402] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:340:in `transition_to'
E, [2015-07-15T13:17:19.993896 #10402] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:160:in `verify'
E, [2015-07-15T13:17:19.993939 #10402] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:189:in `block in test'
E, [2015-07-15T13:17:19.993963 #10402] ERROR -- Kitchen: /opt/rbenv/versions/1.9.3-p547/lib/ruby/1.9.1/benchmark.rb:280:in `measure'
E, [2015-07-15T13:17:19.993988 #10402] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/instance.rb:185:in `test'
E, [2015-07-15T13:17:19.994013 #10402] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/command.rb:176:in `public_send'
E, [2015-07-15T13:17:19.994037 #10402] ERROR -- Kitchen: /my/user/home/.bundle/gems/test-kitchen-1.4.1/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
```

My environment:
RHEL 6.6
rbenv ruby 1.9.3-p547
Nothing fancy in the .kitchen.yml. Declaring block_device_mappings to delete volumes on termination.

Gemfile
```
group :rspec, :kitchen do
  gem 'librarian-puppet', '2.1.0'
  gem 'puppet', puppetversion
  gem 'rspec_junit_formatter'
  gem 'puppet-blacksmith'
  gem 'rspec', '~> 3.3'
end

group :rspec do
  gem 'puppetlabs_spec_helper', '>= 0.1.0'
  gem 'puppet-lint', '< 1.1.0'
  gem 'facter', '>= 1.7.0'
  gem 'rspec-puppet'
  gem 'puppet-syntax'
  gem 'metadata-json-lint'
end

group :kitchen do
  gem 'aws-sdk', '2.1.7'
  gem 'puppet_forge', '<= 1.0.2'
  gem 'test-kitchen'
  gem 'kitchen-puppet'
  gem 'kitchen-docker'
  gem 'kitchen-transport-sshtar'
  gem 'kitchen-vagrant'
  gem 'kitchen-ec2', '0.10.0'
  gem 'vagrant-wrapper'
end
```

The error is rather consistent, but I didn't see this on my Mac with ruby 2.0.0p481.

**Comment by zl4bv** [comment]
Hi @i11, what are the contents of your .kitchen.yml file? Specifically the platform name and image_id if you've specified that.

**Comment by i11** [comment]
Here are driver and platform sections:
```
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV.fetch('AWS_SSH_KEY_ID', 'my-key-id') %>
  security_group_ids: ['my-secure-group']
  subnet_id: my-subnet-id
  region: eu-west-1
  availability_zone: eu-west-1c
  instance_type: t2.micro
  associate_public_ip: true
  interface: private
  retryable_tries: 120

platforms:
  - name: rhel6.6
    driver:
      image_id: my-ami-id
      block_device_mappings:
        - ebs_device_name: /dev/sda1
          ebs_volume_size: 8
          ebs_volume_type: gp2
          ebs_delete_on_termination: true
```

I run it against custom built AMI. It's close to Base installation with puppet per-installed.

By the way I've tested the same setup with ruby 2.1.6 and the problem doesn't persist. It feels like ruby 1.9.3 has something to do with it.

**Comment by zl4bv** [comment]
Looking more closely at the code where the error occurred it seems to be an issue with the aws-sdk library, although even in a new VM with rbenv ruby 1.9.3-p547 I'm having trouble replicating the error.

**Comment by i11** [comment]
Yeah, for some reason it occurs sporadically for me as well and with only a larger number (>20) of suites.

**Comment by jsmickey** [comment]
I am seeing the same error message.  It's inconsistent and I see the problem with Ubuntu and Red Hat. 

---
driver:
  name: ec2
  security_group_ids: ["sg-a123456"]
  region: us-west-2
  availability_zone: us-west-2b
  subnet_id: subnet-1234567
  iam_profile_name: iam-role
  instance_type: t2.small
  associate_pulbic_ip: false
  interface: private
  user_data: test/user_data.sh
  tags:
    Name: test-kitchen

transport:
  username: ubuntu
  ssh_key: ~/.ssh/key.pem
  connection_timeout: 10
  connection_retries: 5

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: ami-123456bw
      block_device_mappings:
        - ebs_device_name: /dev/sda1
          ebs_volume_type: gp2
          ebs_virtual_name: test-kitchen-root
          ebs_volume_size: 10
          ebs_delete_on_termination: true

**Comment by cheeseplus** [comment]
Given that 1.9.3 is EOL so I'm closing this but please re-open if seen under current versions.
