### ISSUE TITLE
Failure to create claims to succeed

### ISSUE THREAD

**Issue by munjeli** [test-kitchen/kitchen-ec2#253]
First off, let me say I love the kitchen-ec2 driver so much, it makes testing wonderful and fun! :heart_eyes_cat: 

However, I periodically see failure to create the instance, probably related to network issues (i suspect because I'm in a vm, and networking is occasionally goofy) but it claims to have created and then fails on converge. The logs aren't helpful. Is there a way to get more verbose logging? Here's the file and the log output. First my .kitchen.yml: this is from my buildserver but I see the issue on other builds too.

``` driver:
  name: docker
  use_sudo: false
  socket: unix:///var/run/docker.sock

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[buildserver::default]
    attributes:

  - name: docker
    run_list:
      - recipe[sbp_packer::default]
      - recipe[buildserver::jenkins]
    attributes:

  - name: ec2
    run_list:
      - recipe[buildserver::jenkins]
      - recipe[buildserver::default]
    driver:
      name: ec2
      region: us-west-2
      aws_ssh_key_id: bootstrap
      instance_type: t2.medium
      availability_zone: a
      subnet_id: <%= ENV['SUBNET_ID'] %>
      security_group_ids: [ <%= ENV['SECURITY_GROUP_ID'] %> ]
      image_id: <%= ENV['AMI_ID'] %>
      tags:
        Name: buildserver
    transport:
      ssh_key: <%= ENV['SSH_PRIVATE_KEY_FILE'] %>
      username: ubuntu
```

Note this config works _most_ of the time. The dockers converge just fine. 
Now the output: 

```
-----> Creating <ec2-ubuntu-1604>...
       Finished creating <ec2-ubuntu-1604> (0m0.00s).
-----> Kitchen is finished. (0m0.46s)
```

Then the converge: 

```
-----> Converging <ec2-ubuntu-1604>...
       Preparing files for transfer
       Preparing dna.json
       Resolving cookbook dependencies with Berkshelf 4.0.1...
       Removing non-cookbook files before transfer
       Preparing validation.pem
       Preparing client.rb
       [SSH] connection failed, retrying in 1 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
       [SSH] connection failed, retrying in 1 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
       [SSH] connection failed, retrying in 1 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
       [SSH] connection failed, retrying in 1 seconds (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
$$$$$$ [SSH] connection failed, terminating (#<Net::SSH::ConnectionTimeout: Net::SSH::ConnectionTimeout>)
>>>>>> Converge failed on instance <ec2-ubuntu-1604>.
>>>>>> Please see .kitchen/logs/ec2-ubuntu-1604.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH session could not be established
>>>>>> ----------------------
```

And destroy: 

```
-----> Destroying <ec2-ubuntu-1604>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #destroy action: [The instance ID 'i-8c60824a' does not exist]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Logs:

```
I, [2016-05-23T13:39:37.398101 #31214]  INFO -- ec2-ubuntu-1604: -----> Destroying <ec2-ubuntu-1604>...
E, [2016-05-23T13:39:37.790813 #31214] ERROR -- ec2-ubuntu-1604: Destroy failed on instance <ec2-ubuntu-1604>.
E, [2016-05-23T13:39:37.791450 #31214] ERROR -- ec2-ubuntu-1604: ------Exception-------
E, [2016-05-23T13:39:37.791477 #31214] ERROR -- ec2-ubuntu-1604: Class: Aws::EC2::Errors::InvalidInstanceIDNotFound
E, [2016-05-23T13:39:37.791488 #31214] ERROR -- ec2-ubuntu-1604: Message: The instance ID 'i-8c60824a' does not exist
E, [2016-05-23T13:39:37.791497 #31214] ERROR -- ec2-ubuntu-1604: ------Backtrace-------
E, [2016-05-23T13:39:37.791505 #31214] ERROR -- ec2-ubuntu-1604: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.13/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
E, [2016-05-23T13:39:37.791514 #31214] ERROR -- ec2-ubuntu-1604: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.13/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
E, [2016-05-23T13:39:37.791522 #31214] ERROR -- ec2-ubuntu-1604: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.13/lib/seahorse/client/plugins/response_target.rb:21:in `call'
E, [2016-05-23T13:39:37.791547 #31214] ERROR -- ec2-ubuntu-1604: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.13/lib/seahorse/client/request.rb:70:in `send_request'
E, [2016-05-23T13:39:37.791556 #31214] ERROR -- ec2-ubuntu-1604: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-core-2.2.13/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
E, [2016-05-23T13:39:37.791564 #31214] ERROR -- ec2-ubuntu-1604: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.2.13/lib/aws-sdk-resources/request.rb:24:in `call'
E, [2016-05-23T13:39:37.791572 #31214] ERROR -- ec2-ubuntu-1604: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.2.13/lib/aws-sdk-resources/operations.rb:41:in `call'
E, [2016-05-23T13:39:37.791582 #31214] ERROR -- ec2-ubuntu-1604: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/aws-sdk-resources-2.2.13/lib/aws-sdk-resources/operation_methods.rb:19:in `block in add_operation'
E, [2016-05-23T13:39:37.791590 #31214] ERROR -- ec2-ubuntu-1604: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/kitchen-ec2-0.10.0/lib/kitchen/driver/ec2.rb:225:in `destroy'
E, [2016-05-23T13:39:37.791598 #31214] ERROR -- ec2-ubuntu-1604: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:431:in `public_send'
E, [2016-05-23T13:39:37.791606 #31214] ERROR -- ec2-ubuntu-1604: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:431:in `block in perform_action'
E, [2016-05-23T13:39:37.791614 #31214] ERROR -- ec2-ubuntu-1604: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:495:in `call'
E, [2016-05-23T13:39:37.791622 #31214] ERROR -- ec2-ubuntu-1604: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:495:in `synchronize_or_call'
E, [2016-05-23T13:39:37.791630 #31214] ERROR -- ec2-ubuntu-1604: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:460:in `block in action'
E, [2016-05-23T13:39:37.791638 #31214] ERROR -- ec2-ubuntu-1604: /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2016-05-23T13:39:37.791645 #31214] ERROR -- ec2-ubuntu-1604: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:459:in `action'
E, [2016-05-23T13:39:37.791655 #31214] ERROR -- ec2-ubuntu-1604: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:431:in `perform_action'
E, [2016-05-23T13:39:37.791663 #31214] ERROR -- ec2-ubuntu-1604: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:418:in `destroy_action'
E, [2016-05-23T13:39:37.791671 #31214] ERROR -- ec2-ubuntu-1604: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:348:in `block in transition_to'
E, [2016-05-23T13:39:37.791679 #31214] ERROR -- ec2-ubuntu-1604: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:347:in `each'
E, [2016-05-23T13:39:37.791693 #31214] ERROR -- ec2-ubuntu-1604: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:347:in `transition_to'
E, [2016-05-23T13:39:37.791702 #31214] ERROR -- ec2-ubuntu-1604: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/instance.rb:171:in `destroy'
E, [2016-05-23T13:39:37.791710 #31214] ERROR -- ec2-ubuntu-1604: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/command.rb:176:in `public_send'
E, [2016-05-23T13:39:37.791718 #31214] ERROR -- ec2-ubuntu-1604: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/test-kitchen-1.5.0/lib/kitchen/command.rb:176:in `block (2 levels) in run_action'
```

It's obvious to me the request is failing, but I don't know where I can set a deeper timeout, or otherwise handle the failure.  It's not about the OS (I've seen this on fedora, and other ubuntus), I have connectivity to ssh and http, etc. Thoughts?

**Comment by munjeli** [comment]
Such a shame, this is an ongoing issue for me. I have had the driver working periodically, but it generally reverts to the fake-out creation with no error. Updating, messing around with my environment and the .kitchen.yml file sometimes gets it going, but the failure rate is high and there's no error messages to really understand what's going on.

**Comment by cheeseplus** [comment]
This dips down into the underlying library Net:SSH and it's definitely barfing on a timeout. The intermittent nature of the errors definitely feels environmental as well so my hunch is that something networky (whether the hypervisor or something along the way) is the culprit.

There is a log level that you can crank the log level to `debug` which can help but the curious thing would be seeing what the host system says regarding ssh connections.

I recognize problems like this are frustrating and the reason it is hard to get traction on these (there are more than a few like this very one) because we can't get a reliable repro case. Run with debug and let us know if you find anything interesting there - that said, once we hand off to net-ssh we're at it's mercy.

**Comment by munjeli** [comment]
Thanks for your response. Yup, I'll set the logs to debug. This driver has been a real boon for working for me since I do all my builds with chef-zero in Packer; debugging the cookbook with some context saves me  the severe nosebleed to trying to debug Chef in Packer. Incidentally, I got it working today after I blew away my .kitchen folder. I also had such a weird time at one point when I was running two ec2 tests on one .kitchen.yml - one was failing and the other succeeding. If I catch it in the act I'll drop something here. Naturally my environment (which is a vm, and cleaner than most prolly) is still not as clean as I'd like.

**Comment by cheeseplus** [comment]
Closing this one out due to lack of response, hopefully things have gotten more stable for you with net-ssh upgrades/fixes that have been pulled in from upstream. If not, please do open a new issue against latest code.
