### ISSUE TITLE
Kitchen create: unable to use IAM profile in 1.3

### ISSUE THREAD

**Issue by jsmickey** [test-kitchen/kitchen-ec2#309]
Scenario: Jenkins instance running on EC2 running kitchen commands to create instances for testing cookbooks.  This works with kitchen-ec2 1.2.0, it fails with 1.3.0 and 1.3.2

EC2 Instance with Instance Profile for AWS access, no environment variables or AWS keys used on the instance
Ubuntu 16.04
ChefDK 1.3.40-1
kitchen-ec2 1.3.2
test-kitchen 1.16.0

```18:31:30 -----> Starting Kitchen (v1.16.0)
18:31:34 -----> Cleaning up any prior instances of <default-ubuntu-1604>
18:31:34 -----> Destroying <default-ubuntu-1604>...
18:31:34        Finished destroying <default-ubuntu-1604> (0m0.00s).
18:31:34 -----> Testing <default-ubuntu-1604>
18:31:34 -----> Creating <default-ubuntu-1604>...
18:31:34 >>>>>> ------Exception-------
18:31:34 >>>>>> Class: Kitchen::ActionFailed
18:31:34 >>>>>> Message: 1 actions failed.
18:31:34 >>>>>>     Failed to complete #create action: [unable to sign request without credentials set] on default-ubuntu-1604
18:31:34 >>>>>> ----------------------
18:31:34 >>>>>> Please see .kitchen/logs/kitchen.log for more details
18:31:34 >>>>>> Also try running `kitchen diagnose --all` for configuration
```

Kitchen log
```
[2017-04-12T16:00:58.145895 #2202] ERROR -- Kitchen: ---Nested Exception---
E, [2017-04-12T16:00:58.145906 #2202] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2017-04-12T16:00:58.145918 #2202] ERROR -- Kitchen: Message: Failed to complete #create action: [unable to sign request without credentials set]
E, [2017-04-12T16:00:58.145930 #2202] ERROR -- Kitchen: ----------------------
E, [2017-04-12T16:00:58.145940 #2202] ERROR -- Kitchen: ------Backtrace-------
E, [2017-04-12T16:00:58.145949 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/request_signer.rb:104:in `require_credentials'
E, [2017-04-12T16:00:58.145960 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/request_signer.rb:94:in `sign_authenticated_requests'
E, [2017-04-12T16:00:58.145970 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/request_signer.rb:87:in `call'
E, [2017-04-12T16:00:58.145981 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
E, [2017-04-12T16:00:58.145991 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/retry_errors.rb:88:in `call'
E, [2017-04-12T16:00:58.146002 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/query/handler.rb:27:in `call'
E, [2017-04-12T16:00:58.146012 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
E, [2017-04-12T16:00:58.146023 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/seahorse/client/plugins/endpoint.rb:41:in `call'
E, [2017-04-12T16:00:58.146033 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
E, [2017-04-12T16:00:58.146043 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
E, [2017-04-12T16:00:58.146054 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
E, [2017-04-12T16:00:58.146064 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
E, [2017-04-12T16:00:58.146074 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
E, [2017-04-12T16:00:58.146085 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
E, [2017-04-12T16:00:58.146108 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/seahorse/client/plugins/response_target.rb:21:in `call'
E, [2017-04-12T16:00:58.146120 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/seahorse/client/request.rb:70:in `send_request'
E, [2017-04-12T16:00:58.146130 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
E, [2017-04-12T16:00:58.146145 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.9.3/lib/aws-sdk-resources/request.rb:24:in `call'
E, [2017-04-12T16:00:58.146157 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.9.3/lib/aws-sdk-resources/operations.rb:41:in `call'
E, [2017-04-12T16:00:58.146167 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.9.3/lib/aws-sdk-resources/operations.rb:61:in `call'
E, [2017-04-12T16:00:58.146178 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.9.3/lib/aws-sdk-resources/resource.rb:147:in `load'
E, [2017-04-12T16:00:58.146191 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.9.3/lib/aws-sdk-resources/resource.rb:120:in `data'
E, [2017-04-12T16:00:58.146203 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.9.3/lib/aws-sdk-resources/resource.rb:223:in `block in add_data_attribute'
E, [2017-04-12T16:00:58.146214 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/kitchen-ec2-1.3.2/lib/kitchen/driver/ec2.rb:588:in `show_chosen_image'
E, [2017-04-12T16:00:58.146224 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/kitchen-ec2-1.3.2/lib/kitchen/driver/ec2.rb:255:in `image'
E, [2017-04-12T16:00:58.146235 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/kitchen-ec2-1.3.2/lib/kitchen/driver/ec2.rb:281:in `actual_platform'
E, [2017-04-12T16:00:58.146246 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/kitchen-ec2-1.3.2/lib/kitchen/driver/ec2.rb:311:in `update_username'
E, [2017-04-12T16:00:58.146256 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/kitchen-ec2-1.3.2/lib/kitchen/driver/ec2.rb:172:in `create'
E, [2017-04-12T16:00:58.146267 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `public_send'
E, [2017-04-12T16:00:58.146277 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `block in perform_action'
E, [2017-04-12T16:00:58.146288 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2017-04-12T16:00:58.146298 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2017-04-12T16:00:58.146309 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-04-12T16:00:58.146320 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
E, [2017-04-12T16:00:58.146344 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `perform_action'
E, [2017-04-12T16:00:58.146356 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:370:in `create_action'
E, [2017-04-12T16:00:58.146367 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2017-04-12T16:00:58.146377 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
E, [2017-04-12T16:00:58.146388 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2017-04-12T16:00:58.146398 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:157:in `verify'
E, [2017-04-12T16:00:58.146409 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:186:in `block in test'
E, [2017-04-12T16:00:58.146419 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2017-04-12T16:00:58.146430 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:182:in `test'
E, [2017-04-12T16:00:58.146440 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
E, [2017-04-12T16:00:58.146451 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-04-12T16:00:58.146461 #2202] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-04-12T16:00:58.146475 #2202] ERROR -- Kitchen: ----End Backtrace-----
```
Debug output
```
D      ------Exception-------
D      Class: Kitchen::ActionFailed
D      Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [unable to sign request without credentials set] on default-ubuntu-1604
D      ----------------------
D      ------Backtrace-------
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:183:in `report_errors'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:174:in `run_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command/action.rb:36:in `block in call'
D      /opt/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command/action.rb:34:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:53:in `perform'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:187:in `block (2 levels) in <class:CLI>'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/cli.rb:334:in `invoke_task'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/bin/kitchen:13:in `block in <top (required)>'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/errors.rb:171:in `with_friendly_errors'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/bin/kitchen:13:in `<top (required)>'
D      /usr/bin/kitchen:21:in `load'
D      /usr/bin/kitchen:21:in `<main>'
D      ----End Backtrace-----
D      -Composite Exception--
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [unable to sign request without credentials set] on default-ubuntu-1604
D      ----------------------
D      ------Backtrace-------
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/request_signer.rb:104:in `require_credentials'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/request_signer.rb:94:in `sign_authenticated_requests'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/request_signer.rb:87:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/retry_errors.rb:88:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/query/handler.rb:27:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/seahorse/client/plugins/endpoint.rb:41:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/seahorse/client/plugins/response_target.rb:21:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/seahorse/client/request.rb:70:in `send_request'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.9.3/lib/aws-sdk-resources/request.rb:24:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.9.3/lib/aws-sdk-resources/operations.rb:41:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.9.3/lib/aws-sdk-resources/operations.rb:61:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.9.3/lib/aws-sdk-resources/resource.rb:147:in `load'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.9.3/lib/aws-sdk-resources/resource.rb:120:in `data'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.9.3/lib/aws-sdk-resources/resource.rb:223:in `block in add_data_attribute'
D      /var/lib/jenkins/.chefdk/gem/ruby/2.3.0/gems/kitchen-ec2-1.3.2/lib/kitchen/driver/ec2.rb:588:in `show_chosen_image'
D      /var/lib/jenkins/.chefdk/gem/ruby/2.3.0/gems/kitchen-ec2-1.3.2/lib/kitchen/driver/ec2.rb:255:in `image'
D      /var/lib/jenkins/.chefdk/gem/ruby/2.3.0/gems/kitchen-ec2-1.3.2/lib/kitchen/driver/ec2.rb:281:in `actual_platform'
D      /var/lib/jenkins/.chefdk/gem/ruby/2.3.0/gems/kitchen-ec2-1.3.2/lib/kitchen/driver/ec2.rb:311:in `update_username'
D      /var/lib/jenkins/.chefdk/gem/ruby/2.3.0/gems/kitchen-ec2-1.3.2/lib/kitchen/driver/ec2.rb:172:in `create'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `public_send'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `block in perform_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
D      /opt/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `perform_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:370:in `create_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:124:in `create'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: Kitchen::ActionFailed
D      Message: Failed to complete #create action: [unable to sign request without credentials set]
D      ----------------------
D      ------Backtrace-------
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/request_signer.rb:104:in `require_credentials'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/request_signer.rb:94:in `sign_authenticated_requests'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/request_signer.rb:87:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/helpful_socket_errors.rb:10:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/retry_errors.rb:88:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/query/handler.rb:27:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/user_agent.rb:12:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/seahorse/client/plugins/endpoint.rb:41:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/param_validator.rb:21:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/seahorse/client/plugins/raise_response_errors.rb:14:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/seahorse/client/plugins/response_target.rb:21:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/seahorse/client/request.rb:70:in `send_request'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-core-2.9.3/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.9.3/lib/aws-sdk-resources/request.rb:24:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.9.3/lib/aws-sdk-resources/operations.rb:41:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.9.3/lib/aws-sdk-resources/operations.rb:61:in `call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.9.3/lib/aws-sdk-resources/resource.rb:147:in `load'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.9.3/lib/aws-sdk-resources/resource.rb:120:in `data'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/aws-sdk-resources-2.9.3/lib/aws-sdk-resources/resource.rb:223:in `block in add_data_attribute'
D      /var/lib/jenkins/.chefdk/gem/ruby/2.3.0/gems/kitchen-ec2-1.3.2/lib/kitchen/driver/ec2.rb:588:in `show_chosen_image'
D      /var/lib/jenkins/.chefdk/gem/ruby/2.3.0/gems/kitchen-ec2-1.3.2/lib/kitchen/driver/ec2.rb:255:in `image'
D      /var/lib/jenkins/.chefdk/gem/ruby/2.3.0/gems/kitchen-ec2-1.3.2/lib/kitchen/driver/ec2.rb:281:in `actual_platform'
D      /var/lib/jenkins/.chefdk/gem/ruby/2.3.0/gems/kitchen-ec2-1.3.2/lib/kitchen/driver/ec2.rb:311:in `update_username'
D      /var/lib/jenkins/.chefdk/gem/ruby/2.3.0/gems/kitchen-ec2-1.3.2/lib/kitchen/driver/ec2.rb:172:in `create'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `public_send'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `block in perform_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
D      /opt/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `perform_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:370:in `create_action'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:124:in `create'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
D      /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
D      ----End Backtrace-----
```

**Comment by saurabh-hirani** [comment]
I am facing the same issue. AWS_PROFILE does not work. But setting AWS_SECRET_ACCESS_KEY and AWS_ACCESS_KEY_ID works.

**Comment by cheeseplus** [comment]
This should be resolved by https://github.com/test-kitchen/kitchen-ec2/pull/353
