### ISSUE TITLE
RequestExpired Error

### ISSUE THREAD

**Issue by jefe78** [test-kitchen/kitchen-ec2#326]
When launching a test I receive the following error:

```
-----> Starting Kitchen (v1.16.0)
-----> Cleaning up any prior instances of <default-ubuntu-1404>
-----> Destroying <default-ubuntu-1404>...
       Finished destroying <default-ubuntu-1404> (0m0.00s).
-----> Testing <default-ubuntu-1404>
-----> Creating <default-ubuntu-1404>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Request has expired.] on default-ubuntu-1404
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration`

The logs show the following:

`cat .kitchen/logs/default-ubuntu-1404.log
I, [2017-07-04T14:38:14.544982 #31795]  INFO -- default-ubuntu-1404: -----> Cleaning up any prior instances of <default-ubuntu-1404>
I, [2017-07-04T14:38:14.545337 #31795]  INFO -- default-ubuntu-1404: -----> Destroying <default-ubuntu-1404>...
I, [2017-07-04T14:38:14.546141 #31795]  INFO -- default-ubuntu-1404: Finished destroying <default-ubuntu-1404> (0m0.00s).
I, [2017-07-04T14:38:14.546826 #31795]  INFO -- default-ubuntu-1404: -----> Testing <default-ubuntu-1404>
I, [2017-07-04T14:38:14.546973 #31795]  INFO -- default-ubuntu-1404: -----> Creating <default-ubuntu-1404>...
E, [2017-07-04T14:38:14.664515 #31795] ERROR -- default-ubuntu-1404: Create failed on instance <default-ubuntu-1404>.
E, [2017-07-04T14:38:14.664665 #31795] ERROR -- default-ubuntu-1404: ------Exception-------
E, [2017-07-04T14:38:14.664689 #31795] ERROR -- default-ubuntu-1404: Class: Aws::EC2::Errors::RequestExpired
E, [2017-07-04T14:38:14.664710 #31795] ERROR -- default-ubuntu-1404: Message: Request has expired.
E, [2017-07-04T14:38:14.664728 #31795] ERROR -- default-ubuntu-1404: ----------------------
E, [2017-07-04T14:38:14.664746 #31795] ERROR -- default-ubuntu-1404: ------Backtrace-------
E, [2017-07-04T14:38:14.664763 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.7/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
E, [2017-07-04T14:38:14.664780 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.7/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
E, [2017-07-04T14:38:14.664799 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.7/lib/aws-sdk-core/plugins/idempotency_token.rb:18:in `call'
E, [2017-07-04T14:38:14.664818 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.7/lib/aws-sdk-core/plugins/param_converter.rb:20:in `call'
E, [2017-07-04T14:38:14.664839 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.7/lib/aws-sdk-core/plugins/response_paging.rb:26:in `call'
E, [2017-07-04T14:38:14.664854 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.7/lib/seahorse/client/plugins/response_target.rb:21:in `call'
E, [2017-07-04T14:38:14.664870 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.7/lib/seahorse/client/request.rb:70:in `send_request'
E, [2017-07-04T14:38:14.664890 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-core-2.10.7/lib/seahorse/client/base.rb:207:in `block (2 levels) in define_operation_methods'
E, [2017-07-04T14:38:14.664906 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-resources-2.10.7/lib/aws-sdk-resources/request.rb:24:in `call'
E, [2017-07-04T14:38:14.664924 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-resources-2.10.7/lib/aws-sdk-resources/operations.rb:41:in `call'
E, [2017-07-04T14:38:14.664939 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-resources-2.10.7/lib/aws-sdk-resources/operations.rb:61:in `call'
E, [2017-07-04T14:38:14.664955 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-resources-2.10.7/lib/aws-sdk-resources/resource.rb:147:in `load'
E, [2017-07-04T14:38:14.664971 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-resources-2.10.7/lib/aws-sdk-resources/resource.rb:120:in `data'
E, [2017-07-04T14:38:14.664988 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/aws-sdk-resources-2.10.7/lib/aws-sdk-resources/resource.rb:223:in `block in add_data_attribute'
E, [2017-07-04T14:38:14.665007 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/kitchen-ec2-1.3.2/lib/kitchen/driver/ec2.rb:590:in `show_chosen_image'
E, [2017-07-04T14:38:14.665025 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/kitchen-ec2-1.3.2/lib/kitchen/driver/ec2.rb:255:in `image'
E, [2017-07-04T14:38:14.665061 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/kitchen-ec2-1.3.2/lib/kitchen/driver/ec2.rb:281:in `actual_platform'
E, [2017-07-04T14:38:14.665081 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/kitchen-ec2-1.3.2/lib/kitchen/driver/ec2.rb:311:in `update_username'
E, [2017-07-04T14:38:14.665098 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/kitchen-ec2-1.3.2/lib/kitchen/driver/ec2.rb:172:in `create'
E, [2017-07-04T14:38:14.665112 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `public_send'
E, [2017-07-04T14:38:14.665126 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `block in perform_action'
E, [2017-07-04T14:38:14.665142 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:527:in `synchronize_or_call'
E, [2017-07-04T14:38:14.665159 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:489:in `block in action'
E, [2017-07-04T14:38:14.665176 #31795] ERROR -- default-ubuntu-1404: /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2017-07-04T14:38:14.665190 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:488:in `action'
E, [2017-07-04T14:38:14.665208 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:460:in `perform_action'
E, [2017-07-04T14:38:14.665224 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:370:in `create_action'
E, [2017-07-04T14:38:14.665242 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:359:in `block in transition_to'
E, [2017-07-04T14:38:14.665260 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `each'
E, [2017-07-04T14:38:14.665279 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:358:in `transition_to'
E, [2017-07-04T14:38:14.665342 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:157:in `verify'
E, [2017-07-04T14:38:14.665361 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:186:in `block in test'
E, [2017-07-04T14:38:14.665380 #31795] ERROR -- default-ubuntu-1404: /usr/local/Cellar/ruby/2.4.0/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2017-07-04T14:38:14.665396 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/instance.rb:182:in `test'
E, [2017-07-04T14:38:14.665415 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `public_send'
E, [2017-07-04T14:38:14.665433 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2017-07-04T14:38:14.665449 #31795] ERROR -- default-ubuntu-1404: /usr/local/lib/ruby/gems/2.4.0/gems/test-kitchen-1.16.0/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2017-07-04T14:38:14.665467 #31795] ERROR -- default-ubuntu-1404: ----End Backtrace-----
```

My .kitchen.yml file looks like this:

```
---
driver:
  name: ec2
  aws_ssh_key_id: sandbox
  security_group_ids: ["sg-****"]
  region: us-west-2
  availability_zone: a
  require_chef_omnibus: true
  subnet_id: subnet-****
  iam_profile_name: test
  instance_type: m3.medium
  associate_public_ip: true

transport:
  ssh_key: /Users/***/.ssh/sandbox.pem
  connection_timeout: 10
  connection_retries: 5
  username: ubuntu

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: ami-fc4f5e85
      block_device_mappings:
        - device_name: /dev/sda1
          ebs:
            volume_type: gp2
            virtual_name: test
            volume_size: 15
            delete_on_termination: true

suites:
  - name: default
    run_list:
      - recipe[base::default]`
```

I'm not sure what the issue is. I tested the IAM credentials and they work fine. Thanks!

**Comment by cheeseplus** [comment]
This usually is only thrown if it takes more than 15 minutes for the request to be serviced. I'd check to make sure your clocks are in sync or that this isn't hanging on that create.
