### ISSUE TITLE
How to sync local folders

### ISSUE THREAD

**Issue by Shplorf** [test-kitchen/kitchen-ec2#418]
When using the vagrant driver this is accomplished by using the `synced_folders` property. Is there anything equivalent in this driver?
I need to be able to grab the logs of the app I'm testing and copy them back to the CI runner that is running kitchen so it can publish them as artifacts. Would appreciate suggestions as to how to accomplish this.
Thanks!

**Comment by cheeseplus** [comment]
There is no analogue in most other drivers as that's a very specific feature of the local hypervisors that Vagrant supports. Lifecycle hooks might be appropriate for pulling data back or pushing it from the instance itself: https://github.com/test-kitchen/test-kitchen/blob/master/RELEASE_NOTES.md#life-cycle-hooks

**Comment by Shplorf** [comment]
Thanks for clearing that up!

**Comment by coderanger** [comment]
You can also use the `data_path` option of the Chef provisioners to sync a specific folder with test fixture data, though it's unidirectional (i.e. the folder is copied along with your cookbooks).

**Comment by Shplorf** [comment]
@cheeseplus OK it is a little messy (partially because the log files in question are owned by root) but I got what I wanted:
```
lifecycle:
  post_verify:
    - local: ssh -i $AWS_SSH_KEY ubuntu@$KITCHEN_INSTANCE_HOSTNAME "sudo cat /path/to/my/logs/a_log.log" > ./logs/${KITCHEN_PLATFORM_NAME}_${KITCHEN_SUITE_NAME}_a_log.log
```
Thanks again!

**Comment by Shplorf** [comment]
@cheeseplus hmm is the post_verify hook not triggered when there are test failures?

**Comment by Shplorf** [comment]
Hmm ok @cheeseplus , that seems to be the behavior I'm seeing, but when I try to instead do:
```
lifecycle:
  pre_destroy:
    - local: cmd
      skippable: true
```
I get the following error:
```
E, [2018-09-27T08:59:03.159113 #53982] ERROR -- Kitchen: ------Exception-------
E, [2018-09-27T08:59:03.159145 #53982] ERROR -- Kitchen: Class: Mixlib::ShellOut::InvalidCommandOption
E, [2018-09-27T08:59:03.159166 #53982] ERROR -- Kitchen: Message: option ':skippable' is not a valid option for Mixlib::ShellOut
E, [2018-09-27T08:59:03.159184 #53982] ERROR -- Kitchen: ----------------------
E, [2018-09-27T08:59:03.159200 #53982] ERROR -- Kitchen: ------Backtrace-------
E, [2018-09-27T08:59:03.159216 #53982] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/mixlib-shellout-2.4.0/lib/mixlib/shellout.rb:355:in `block in parse_options'
E, [2018-09-27T08:59:03.159233 #53982] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/mixlib-shellout-2.4.0/lib/mixlib/shellout.rb:309:in `each'
E, [2018-09-27T08:59:03.159250 #53982] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/mixlib-shellout-2.4.0/lib/mixlib/shellout.rb:309:in `parse_options'
E, [2018-09-27T08:59:03.159266 #53982] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/mixlib-shellout-2.4.0/lib/mixlib/shellout.rb:184:in `initialize'
E, [2018-09-27T08:59:03.159281 #53982] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/shell_out.rb:65:in `new'
E, [2018-09-27T08:59:03.159298 #53982] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/shell_out.rb:65:in `run_command'
E, [2018-09-27T08:59:03.159314 #53982] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:111:in `run_local_hook'
E, [2018-09-27T08:59:03.159331 #53982] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:70:in `block in run'
E, [2018-09-27T08:59:03.159347 #53982] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:64:in `each'
E, [2018-09-27T08:59:03.159625 #53982] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:64:in `run'
E, [2018-09-27T08:59:03.159642 #53982] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:44:in `run_with_hooks'
E, [2018-09-27T08:59:03.159659 #53982] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:381:in `block in transition_to'
E, [2018-09-27T08:59:03.159674 #53982] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `each'
E, [2018-09-27T08:59:03.159691 #53982] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `transition_to'
E, [2018-09-27T08:59:03.159707 #53982] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:173:in `destroy'
E, [2018-09-27T08:59:03.159723 #53982] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:189:in `block in test'
E, [2018-09-27T08:59:03.159738 #53982] ERROR -- Kitchen: /Users/gregmalkov/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2018-09-27T08:59:03.159754 #53982] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:187:in `test'
E, [2018-09-27T08:59:03.159786 #53982] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `public_send'
E, [2018-09-27T08:59:03.159803 #53982] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2018-09-27T08:59:03.159819 #53982] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2018-09-27T08:59:03.159836 #53982] ERROR -- Kitchen: ----End Backtrace-----
```

**Comment by Shplorf** [comment]
So it looks like `skippable` is not implemented for `local`?

I instead tried this:
```
lifecycle:
  pre_destroy:
    - local: 'nc -G 2 $KITCHEN_INSTANCE_HOSTNAME 22 && ssh -i $AWS_SSH_KEY ubuntu@$KITCHEN_INSTANCE_HOSTNAME "sudo cat /path/to/my/logs/a_log.log" > ./logs/${KITCHEN_PLATFORM_NAME}_${KITCHEN_SUITE_NAME}_a_log.log || true'
```
So basically only running that command if I can reach the target host via ssh. However I then ran into the following:
```
E, [2018-09-27T10:19:14.337030 #55080] ERROR -- Kitchen: ------Exception-------
E, [2018-09-27T10:19:14.337147 #55080] ERROR -- Kitchen: Class: Kitchen::UserError
E, [2018-09-27T10:19:14.337280 #55080] ERROR -- Kitchen: Message: Unknown lifecycle hook target {}
E, [2018-09-27T10:19:14.337352 #55080] ERROR -- Kitchen: ----------------------
E, [2018-09-27T10:19:14.337415 #55080] ERROR -- Kitchen: ------Backtrace-------
E, [2018-09-27T10:19:14.337475 #55080] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:75:in `block in run'
E, [2018-09-27T10:19:14.337535 #55080] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:64:in `each'
E, [2018-09-27T10:19:14.337595 #55080] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:64:in `run'
E, [2018-09-27T10:19:14.337654 #55080] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:44:in `run_with_hooks'
E, [2018-09-27T10:19:14.337714 #55080] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:381:in `block in transition_to'
E, [2018-09-27T10:19:14.337773 #55080] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `each'
E, [2018-09-27T10:19:14.337832 #55080] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `transition_to'
E, [2018-09-27T10:19:14.337892 #55080] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:173:in `destroy'
E, [2018-09-27T10:19:14.337951 #55080] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:192:in `block in test'
E, [2018-09-27T10:19:14.338024 #55080] ERROR -- Kitchen: /Users/gregmalkov/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/benchmark.rb:293:in `measure'
E, [2018-09-27T10:19:14.338088 #55080] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:187:in `test'
E, [2018-09-27T10:19:14.338150 #55080] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `public_send'
E, [2018-09-27T10:19:14.338226 #55080] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
E, [2018-09-27T10:19:14.338304 #55080] ERROR -- Kitchen: /Users/gregmalkov/threatstack/agent-test/vendor/cache/ruby/2.4.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
E, [2018-09-27T10:19:14.338370 #55080] ERROR -- Kitchen: ----End Backtrace-----
```
Debugging this, it seems like for some reason when this hook is processed at the post-test destroy phase, the `hook_data` variable at `lifecycle_hooks.rb:68` is an array with one empty hash. The pre-test destroy phase works just fine though...

I'll keep poking at it 🤔

**Comment by Shplorf** [comment]
Hmm so it seems likely that it has something to do with this:
`lifecycle_hooks.rb:87`:`cmd = hook.delete(:local)`
The hook is deleted, so it can't be executed twice. But in the `test` case it needs to be, both before and after testing 🤔 
@cheeseplus Should I write up a separate issue for hooks triggering multiple times in a run not working?

**Comment by cheeseplus** [comment]
You don't need to keep pinging me directly - feel free to open a new issue, if anything @coderanger will be the one to determine whether it's a bug or as designed as they wrote the system

**Comment by Shplorf** [comment]
OK, yeah sorry for poking you so much. For now my workaround is:
```
lifecycle:
  pre_verify:
    - local: 'nohup ssh ubuntu@$KITCHEN_INSTANCE_HOSTNAME "while ! sudo tail -fn +1 /path/to/my/logs/a_log.log ; do sleep 1; done" >> ./logs/${KITCHEN_PLATFORM_NAME}_a_log.log 2>&1 &'
```
