### ISSUE TITLE
Unable to SSH into VPC Instance

### ISSUE THREAD

**Issue by jmassara** [test-kitchen/kitchen-ec2#77]
I am attempting to create an instance inside of a VPC with the following configuration, however it just hangs attempting to connect and ultimately times out.  While it's attempting to connect, in another terminal window I am able to manually SSH in without a problem.

What am I doing wrong?

```ruby
---
driver_config:
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR_NAME'] %>
  username: ec2-user

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.4
  environments_path: "test/integration/default/environments"
  data_bags_path: "test/integration/default/data_bags"
  client_rb:
    environment: aws
    ssl_verify_mode: verify_peer

platforms:
- name: rhel-7.0
  driver_plugin: ec2
  driver_config:
    region: us-west-1
    availability_zone: us-west-1a
    security_group_ids: ["sg-XXXXXXXX"]
    subnet_id: subnet-XXXXXXXX
    associate_public_ip: false
    iam_profile_name: test-role
    image_id: ami-35cdd870
    flavor_id: c3.large

suites:
- name: default
  run_list: ["recipe[test]"]
```

**Comment by jmassara** [comment]
@dtoubelis Sorry for the delay, wasn't around for the holidays!

I've done some more testing, and when I use this gem (pulled from rubygems), it works.  However, because I need IAM role support (see #54), I need to pull the master branch directly.  When I use the master branch, I get the timeouts.  Whether or not I specify `ssh_key` doesn't seem to matter.  Note that even though test kitchen times out, in a separate shell I can ssh in just fine.

Log output:
```
I, [2015-01-06T12:00:33.250534 #89149]  INFO -- default-rhel-70: -----> Creating <default-rhel-70>...
I, [2015-01-06T12:00:33.250623 #89149]  INFO -- default-rhel-70: Creating <>...
I, [2015-01-06T12:00:33.250652 #89149]  INFO -- default-rhel-70: If you are not using an account that qualifies under the AWS
I, [2015-01-06T12:00:33.250671 #89149]  INFO -- default-rhel-70: free-tier, you may be charged to run these suites. The charge
I, [2015-01-06T12:00:33.250689 #89149]  INFO -- default-rhel-70: should be minimal, but neither Test Kitchen nor its maintainers
I, [2015-01-06T12:00:33.250706 #89149]  INFO -- default-rhel-70: are responsible for your incurred costs.
I, [2015-01-06T12:00:35.228032 #89149]  INFO -- default-rhel-70: EC2 instance <i-66e5ceae> created.
E, [2015-01-06T12:10:37.177161 #89149] ERROR -- default-rhel-70: Create failed on instance <default-rhel-70>.
E, [2015-01-06T12:10:37.177308 #89149] ERROR -- default-rhel-70: ------Exception-------
E, [2015-01-06T12:10:37.177340 #89149] ERROR -- default-rhel-70: Class: Kitchen::ActionFailed
E, [2015-01-06T12:10:37.177363 #89149] ERROR -- default-rhel-70: Message: The specified wait_for timeout (600 seconds) was exceeded
E, [2015-01-06T12:10:37.177385 #89149] ERROR -- default-rhel-70: ---Nested Exception---
E, [2015-01-06T12:10:37.177406 #89149] ERROR -- default-rhel-70: Class: Fog::Errors::TimeoutError
E, [2015-01-06T12:10:37.177426 #89149] ERROR -- default-rhel-70: Message: The specified wait_for timeout (600 seconds) was exceeded
E, [2015-01-06T12:10:37.177447 #89149] ERROR -- default-rhel-70: ------Backtrace-------
E, [2015-01-06T12:10:37.177467 #89149] ERROR -- default-rhel-70: /Users/jmassara/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/kitchen-ec2-12b771924900/lib/kitchen/driver/ec2.rb:109:in `rescue in create'
E, [2015-01-06T12:10:37.179054 #89149] ERROR -- default-rhel-70: /Users/jmassara/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/kitchen-ec2-12b771924900/lib/kitchen/driver/ec2.rb:77:in `create'
E, [2015-01-06T12:10:37.179116 #89149] ERROR -- default-rhel-70: /Users/jmassara/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:273:in `public_send'
E, [2015-01-06T12:10:37.179134 #89149] ERROR -- default-rhel-70: /Users/jmassara/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:273:in `block in perform_action'
E, [2015-01-06T12:10:37.179149 #89149] ERROR -- default-rhel-70: /Users/jmassara/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:308:in `call'
E, [2015-01-06T12:10:37.179163 #89149] ERROR -- default-rhel-70: /Users/jmassara/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:308:in `synchronize_or_call'
E, [2015-01-06T12:10:37.179177 #89149] ERROR -- default-rhel-70: /Users/jmassara/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:283:in `block in action'
E, [2015-01-06T12:10:37.179191 #89149] ERROR -- default-rhel-70: /Users/jmassara/.rbenv/versions/2.1.2/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2015-01-06T12:10:37.179205 #89149] ERROR -- default-rhel-70: /Users/jmassara/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:282:in `action'
E, [2015-01-06T12:10:37.179219 #89149] ERROR -- default-rhel-70: /Users/jmassara/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:273:in `perform_action'
E, [2015-01-06T12:10:37.179233 #89149] ERROR -- default-rhel-70: /Users/jmassara/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:252:in `create_action'
E, [2015-01-06T12:10:37.179247 #89149] ERROR -- default-rhel-70: /Users/jmassara/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:246:in `block in transition_to'
E, [2015-01-06T12:10:37.179260 #89149] ERROR -- default-rhel-70: /Users/jmassara/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:245:in `each'
E, [2015-01-06T12:10:37.179274 #89149] ERROR -- default-rhel-70: /Users/jmassara/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:245:in `transition_to'
E, [2015-01-06T12:10:37.179287 #89149] ERROR -- default-rhel-70: /Users/jmassara/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.2.1/lib/kitchen/instance.rb:119:in `converge'
E, [2015-01-06T12:10:37.179301 #89149] ERROR -- default-rhel-70: /Users/jmassara/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.2.1/lib/kitchen/command.rb:109:in `public_send'
E, [2015-01-06T12:10:37.179314 #89149] ERROR -- default-rhel-70: /Users/jmassara/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/test-kitchen-1.2.1/lib/kitchen/command.rb:109:in `block (2 levels) in run_action'
E, [2015-01-06T12:10:37.179328 #89149] ERROR -- default-rhel-70: ----------------------
```

**Comment by sheldonh** [comment]
Happens to me too, with chef-dk and the following .kitchen.yml:

```
---
driver:
  name: ec2
  aws_access_key_id: ...
  aws_secret_access_key: ...
  aws_session_token: ...
  aws_ssh_key_id: chef-lab
  ssh_key: <%= ENV['HOME'] %>/.ssh/chef-lab.pem
  subnet_id: subnet-XXXXXXXX
  security_group_ids:
    - sg-XXXXXXXX
  require_chef_omnibus: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    driver:
      image_id: ami-9eaa1cf6
      username: ubuntu
      flavor_id: t2.micro

suites:
  - name: default
    run_list:
      - recipe[getting-started::default]
    attributes:
```

**Comment by tyler-ball** [comment]
Can yall try with the latest kitchen-ec2 release (0.9.0)?  I should have fixed this there and it also includes the fix for including `iam_profile_name`.  If you are still having an issue please re-open this!
