### ISSUE TITLE
Issue with amazon linux 32 bit and SCP failing >>>>>> Message: Failed to complete #converge action: [SCP did not finish successfully (127): ]

### ISSUE THREAD

**Issue by petecheslock** [test-kitchen/kitchen-ec2#88]
snip from the tk.yml
```
  - name: amazon-ami-2014.09-32
    driver:
      image_id: ami-16852c7e
      flavor_id: c1.medium
      username: ec2-user
    run_list:
      - recipe[yum]
```

```
kitchen converge default-amazon-ami-201409-32
-----> Starting Kitchen (v1.2.1)
-----> Creating <default-amazon-ami-201409-32>...
       Creating <>...
       If you are not using an account that qualifies under the AWS
       free-tier, you may be charged to run these suites. The charge
       should be minimal, but neither Test Kitchen nor its maintainers
       are responsible for your incurred costs.
       EC2 instance <i-c1f4a93a> created.
.....................       (server ready)
       Waiting for ec2-54-88-70-203.compute-1.amazonaws.com:22...
       Waiting for ec2-54-88-70-203.compute-1.amazonaws.com:22...
       Waiting for ec2-54-88-70-203.compute-1.amazonaws.com:22...
       Waiting for ec2-54-88-70-203.compute-1.amazonaws.com:22...
       Waiting for ec2-54-88-70-203.compute-1.amazonaws.com:22...
       Waiting for ec2-54-88-70-203.compute-1.amazonaws.com:22...
       Waiting for ec2-54-88-70-203.compute-1.amazonaws.com:22...
       (ssh ready)

       Finished creating <default-amazon-ami-201409-32> (1m2.42s).
-----> Converging <default-amazon-ami-201409-32>...
       Preparing files for transfer
       Resolving cookbook dependencies with Berkshelf 3.2.1...
       Removing non-cookbook files before transfer
-----> Installing Chef Omnibus (11.16.4)
       downloading https://www.getchef.com/chef/install.sh
         to file /tmp/install.sh
       trying curl...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current

                               Dload  Upload   Total   Spent    Left  Spee       d
100   178  100   178    0     0    611      0 --:--:-- --:--:-- --:--:--   61       1
100 18265  100 18265    0     0  36728      0 --:--:-- --:--:-- --:--:-- 3672       8
       Downloading Chef 11.16.4 for el...
       downloading https://www.chef.io/chef/metadata?v=11.16.4&prerelease=false&nightlies=false&p=el&pv=6&m=i686
         to file /tmp/install.sh.1249/metadata.txt
       trying curl...
       url      https://opscode-omnibus-packages.s3.amazonaws.com/el/6/i686/chef-11.16.4-1.el6.i686.rpm
       md5      da7bbe41d9510de62adf6afe89ed2ecd
       sha256   545075be04de512c780c961b3aa3809c4540fd68c47c167eced67a8daa0821b7
       downloaded metadata file looks valid...
       downloading https://opscode-omnibus-packages.s3.amazonaws.com/el/6/i686/chef-11.16.4-1.el6.i686.rpm
         to file /tmp/install.sh.1249/chef-11.16.4-1.el6.i686.rpm
       trying curl...
       Comparing checksum with sha256sum...
       Installing Chef 11.16.4
       installing with rpm...
warning:        /tmp/install.sh.1249/chef-11.16.4-1.el6.i686.rpm: Header V4 DSA/SHA1 Signature, key ID 83ef826a: NOKEY
Preparing...                                 ################################# [100%]
       Updating / installing...
   1:chef-11.16.4-1.el6                      ################################# [100%]
       Thank you for installing Chef!
       Transfering files to <default-amazon-ami-201409-32>
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [SCP did not finish successfully (127): ]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
```
I, [2015-01-11T17:01:40.179529 #40963]  INFO -- Kitchen: -----> Starting Kitchen (v1.2.1)
I, [2015-01-11T17:01:42.041765 #40963]  INFO -- Kitchen: -----> Creating <default-amazon-ami-201409-32>...
I, [2015-01-11T17:02:44.468030 #40963]  INFO -- Kitchen: -----> Converging <default-amazon-ami-201409-32>...
E, [2015-01-11T17:02:52.606947 #40963] ERROR -- Kitchen: ------Exception-------
E, [2015-01-11T17:02:52.606997 #40963] ERROR -- Kitchen: Class: Kitchen::ActionFailed
E, [2015-01-11T17:02:52.607025 #40963] ERROR -- Kitchen: Message: Failed to complete #converge action: [SCP did not finish successfully (127): ]
E, [2015-01-11T17:02:52.607054 #40963] ERROR -- Kitchen: ---Nested Exception---
E, [2015-01-11T17:02:52.607078 #40963] ERROR -- Kitchen: Class: Net::SCP::Error
E, [2015-01-11T17:02:52.607101 #40963] ERROR -- Kitchen: Message: SCP did not finish successfully (127):
E, [2015-01-11T17:02:52.607122 #40963] ERROR -- Kitchen: ------Backtrace-------
E, [2015-01-11T17:02:52.607157 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-scp-1.2.1/lib/net/scp.rb:365:in `block (3 levels) in start_command'
E, [2015-01-11T17:02:52.607204 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:591:in `call'
E, [2015-01-11T17:02:52.607231 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:591:in `do_close'
E, [2015-01-11T17:02:52.607257 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:586:in `channel_close'
E, [2015-01-11T17:02:52.607281 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:465:in `dispatch_incoming_packets'
E, [2015-01-11T17:02:52.607305 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:221:in `preprocess'
E, [2015-01-11T17:02:52.607345 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:205:in `process'
E, [2015-01-11T17:02:52.607370 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `block in loop'
E, [2015-01-11T17:02:52.607394 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
E, [2015-01-11T17:02:52.607420 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
E, [2015-01-11T17:02:52.607463 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-ssh-2.9.1/lib/net/ssh/connection/channel.rb:269:in `wait'
E, [2015-01-11T17:02:52.607488 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/net-scp-1.2.1/lib/net/scp.rb:284:in `upload!'
E, [2015-01-11T17:02:52.607521 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/ssh.rb:70:in `upload!'
E, [2015-01-11T17:02:52.607545 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/ssh.rb:76:in `upload_path!'
E, [2015-01-11T17:02:52.607576 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/driver/ssh_base.rb:119:in `block in transfer_path'
E, [2015-01-11T17:02:52.607600 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/driver/ssh_base.rb:119:in `each'
E, [2015-01-11T17:02:52.607638 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/driver/ssh_base.rb:119:in `transfer_path'
E, [2015-01-11T17:02:52.607662 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/driver/ssh_base.rb:46:in `block in converge'
E, [2015-01-11T17:02:52.607686 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/ssh.rb:47:in `initialize'
E, [2015-01-11T17:02:52.607709 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/driver/ssh_base.rb:43:in `new'
E, [2015-01-11T17:02:52.607746 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/driver/ssh_base.rb:43:in `converge'
E, [2015-01-11T17:02:52.607771 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:273:in `public_send'
E, [2015-01-11T17:02:52.607795 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:273:in `block in perform_action'
E, [2015-01-11T17:02:52.607819 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:308:in `call'
E, [2015-01-11T17:02:52.607991 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:308:in `synchronize_or_call'
E, [2015-01-11T17:02:52.608025 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:283:in `block in action'
E, [2015-01-11T17:02:52.608053 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/lib/ruby/2.1.0/benchmark.rb:279:in `measure'
E, [2015-01-11T17:02:52.608085 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:282:in `action'
E, [2015-01-11T17:02:52.608110 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:273:in `perform_action'
E, [2015-01-11T17:02:52.608147 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:256:in `converge_action'
E, [2015-01-11T17:02:52.608173 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:246:in `block in transition_to'
E, [2015-01-11T17:02:52.608201 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:245:in `each'
E, [2015-01-11T17:02:52.608226 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:245:in `transition_to'
E, [2015-01-11T17:02:52.608276 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/instance.rb:119:in `converge'
E, [2015-01-11T17:02:52.608308 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:109:in `public_send'
E, [2015-01-11T17:02:52.608353 #40963] ERROR -- Kitchen: /opt/chefdk/embedded/apps/test-kitchen/lib/kitchen/command.rb:109:in `block (2 levels) in run_action'
E, [2015-01-11T17:02:52.608381 #40963] ERROR -- Kitchen: ----------------------
```

using TK version 
```
kitchen --version
Test Kitchen version 1.2.1
```
from Chef DK version:
```
chef --version
Chef Development Kit Version: 0.3.5
```

Has anyone been able to converge a TK run on a 32 bit Amazon Linux node?

**Comment by petecheslock** [comment]
Hrm - using master of kitchen-ec2 and test-kichen seems to work - so maybe the fix is already in master?

**Comment by petecheslock** [comment]
Yea - testing off of master on both projects looks like this is fixes probably a newer version of Net::SCP or something?
